### ISSUE TITLE
Migrate `app_configuration_keys` module from MDP

### ISSUE THREAD

**Issue by MikeEvansLarah** [endjin/Endjin.RecommendedPractices.Bicep#53]
ref: https://github.com/endjin/modern-data-platform/blob/master/bicep/modules/app_configuration_keys.bicep

**Comment by MikeLarah** [comment]
Module already exists:

https://github.com/endjin/Endjin.RecommendedPractices.Bicep/blob/main/modules/general/set-app-configuration-keys/main.bicep
